name: Upstream Sync

on:
  schedule:
    - cron:  '0 * * * *' # 1時間に1回実行
  workflow_dispatch: # 手動実行ボタンも有効化

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Sync upstream changes
        id: sync
        uses: aieri/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/SpigotMC/BungeeCord.git
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
